services:
  redis:
    image: "unibot_rag/unibot_rag:redis-db"
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"
    build:
      context: .
      dockerfile: redis.dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}

  backend:
    image: "unibot_rag/unibot_rag:backend-test"
    ports:
      # - 81:81
      - 8501:8501
    volumes:
      - ./unibot_RAG:/unibot_RAG
      - ./credentials.json:/gcp/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials.json
    depends_on:
      - redis
    env_file:
      - .env
    build:
      context: ./
      dockerfile: backend.dockerfile

volumes:
  redis_data:
    driver: local
